### ISSUE TITLE
택배 조회 시 파라미터 사이의 공백 문자열 처리 방법 수정

### ISSUE THREAD

**Issue by inc5025** [webdonalds/discord-bot#28]
- 기존은 파라미터 사이의 공백은 무조건 스페이스 하나가 들어가야함
- 공백으로 스페이스 2개가 들어가든, 탭이 들어가든 공백 문자열이면 정상적으로 동작되면 좋겠음

**Comment by hellodhlyn** [comment]
https://github.com/webdonalds/discord-bot/issues/31 에서 해결
