### ISSUE TITLE
ExchangeCommand 개선

### ISSUE THREAD

**Issue by bomul0327** [webdonalds/discord-bot#4]
Json 데이터를 파싱할 때, 그냥 interface로 캐스팅하지 말고 response되는 타입을 만들어줄 것

**Comment by zych1751** [comment]
https://stackoverflow.com/questions/17156371/how-to-get-json-response-from-http-get
참고하면 좋을것 같슴니당

**Comment by bomul0327** [comment]
테스트

**Comment by zych1751** [comment]
@inc5025 일 안하세요?

**Comment by zych1751** [comment]
환율 API response json의 key값이 request에 따라 달라져서 지금 구현되어 있는것 처럼 직접 파싱을 하는게 맞아보입니다.

현재 이슈 닫겠습니다.
